# Generated by Django 2.0.3 on 2018-04-09 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataitem',
            name='previous_hash',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
